# Generated by Django 4.0.1 on 2022-01-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
                ('tarih', models.DateField(null=True)),
                ('yazar', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
